### ISSUE TITLE
Clipped rendering on Windows

### ISSUE THREAD

**Issue by RazrFalcon** [pcwalton/font-kit#85]
Looks like a rendering canvas doesn't have an enough space.

```
>cargo run --example render-glyph -- ArialMT { 32
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target\debug\examples\render-glyph.exe ArialMT { 32`
glyph 94:






            ▓▓██████
          ██████████
        ▒▒████▒▒
        ▓▓██▓▓
        ▓▓██▓▓
        ▓▓██▓▓
        ▓▓██▓▓
        ▓▓██▓▓
        ▓▓██▓▓
        ████▓▓
        ████▒▒
      ▒▒████▒▒
    ▒▒████▓▓
░░████████
░░████▒▒
░░████████
    ▒▒████▓▓
      ▒▒████▒▒
      ░░████▒▒
        ████▓▓
        ▓▓██▓▓
        ▓▓██▓▓
        ▓▓██▓▓

```

Works correctly on Linux. Not sure about macOS. 

@pcwalton I'm not familiar with dwrite. Can you take a look?

**Comment by kud1ing** [comment]
> Not sure about macOS.

Seems to be complete on macOS:

```
glyph 94:
          ░░▒▒▓▓▓▓▓▓
        ░░▓▓████████
        ▒▒██████████
        ▓▓████▓▓░░░░
      ░░██████░░    
      ░░██████░░    
      ░░██████░░    
      ░░██████░░    
      ░░██████░░    
      ░░██████░░    
      ░░████▓▓      
      ▒▒████▓▓      
    ░░▓▓████▒▒      
░░▒▒▓▓██████░░      
▒▒██████▓▓▒▒        
▒▒██████▓▓░░        
▒▒████████▒▒        
░░░░▓▓██████░░      
    ░░▓▓████▒▒      
      ▒▒████▓▓      
      ░░████▓▓      
      ░░██████░░    
      ░░██████░░    
      ░░██████░░    
      ░░██████░░    
      ░░██████░░    
      ░░██████▒▒    
        ▓▓████▓▓▒▒▒▒
        ▒▒██████████
        ░░▓▓████████
          ░░▒▒▒▒▓▓▓▓
```

**Comment by idursun** [comment]
A little bit input about the issue:

Clipping is occurring because `dwrite_analysis.get_alpha_texture_bounds` is returning negative top values for char {.

Changing the following line 
https://github.com/pcwalton/font-kit/blob/2fd68a8e932d43d498d58021d6fc78c0c0eef81f/src/loaders/directwrite.rs#L481
to
```rust
point2(0,0)
```
is fixing the clipping in the example but messing up the baselining. (I am not sure if this is the right term to use)

I have tried `silicon` with the modified local version of `font-kit` and this is how it renders after the change. 

![image](https://user-images.githubusercontent.com/103216/61668852-faf6ca80-acd5-11e9-9d31-ac6c6a11f10c.png)
